version: 3
tasks:
  run:
    cmd: go run .
  run-debug:
    cmd: go run . --debug
  test:
    cmd: go test -v ./...
  clean:
    cmd: rm -rf ./dist
  tag:
    desc: Create a new version tag and GitHub release with changelog
    cmds:
      - VERSION=$(git cliff --bumped-version) && git tag $VERSION && git push origin $VERSION && git cliff -l -s all | gh release create $VERSION --notes-file -
  release:
    cmd: goreleaser release

  check:
    cmds:
      - goreleaser healthcheck
