#name: release
#
#on:
#  push:
#    tags:
#      - "v*"
#
#permissions:
#  contents: write
#  id-token: write
#  packages: write
#
#jobs:
#  goreleaser:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#        with:
#          fetch-depth: 0
#      - uses: actions/setup-go@v5
#        with:
#          go-version: stable
#      - uses: goreleaser/goreleaser-action@v6
#        with:
#          version: latest
#          args: release --clean
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cli/gh-extension-precompile@v2
        with:
          generate_attestations: true
          go_version_file: go.mod
